# Generated by Django 3.2 on 2021-05-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'get_latest_by': ['name'], 'ordering': ['name']},
        ),
    ]
