# Generated by Django 3.2 on 2021-06-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_accessbytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessbytoken',
            name='is_active',
            field=models.SmallIntegerField(choices=[(1, 'active'), (0, 'rotten')], default=0, verbose_name='Состояние'),
        ),
    ]
