# Generated by Django 3.2 on 2021-08-23 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_bytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bytoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_user', related_query_name='query_user', to='books.publisher'),
        ),
    ]
