version: "3.7"
services:
  web:
    build: .
    command: python /usr/src/dockerproba/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/dockerproba
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:5.7
    expose:
      - "3308"
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "dj"
      MYSQL_USER: "alameda"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql