# Generated by Django 3.1.7 on 2021-04-03 10:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Game')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='startGame')),
                ('date_end', models.DateTimeField(verbose_name='endGame')),
                ('status', models.SmallIntegerField(default=1)),
                ('winner', models.CharField(max_length=50, verbose_name='Победитель')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('ship', models.CharField(max_length=250)),
                ('status', models.SmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajax.game', verbose_name='UUID')),
            ],
        ),
    ]
