# Generated by Django 3.1.7 on 2021-04-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'ready'), (2, 'not_ready')]),
        ),
    ]
