# Generated by Django 3.1.7 on 2021-04-03 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0002_auto_20210403_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_end',
            field=models.DateTimeField(help_text='время окончания игры', null=True, verbose_name='endGame'),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Started'), (0, 'Finished')], default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(max_length=50, null=True, verbose_name='Победитель'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ship',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'ready'), (2, 'not_ready')], default=2),
        ),
    ]
